# Generated by Django 3.1 on 2021-05-24 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('StandardCost', models.FloatField(null=True)),
                ('daysToManufacture', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('group', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('customer', models.IntegerField(null=True)),
                ('total', models.FloatField(null=True)),
                ('salesPerson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.seller')),
                ('territory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.territory')),
            ],
        ),
        migrations.CreateModel(
            name='detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderyQty', models.IntegerField(null=True)),
                ('UnitPrice', models.FloatField(null=True)),
                ('LineTotal', models.FloatField(null=True)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.product')),
            ],
        ),
    ]
