# Generated by Django 3.1 on 2021-05-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_detalle_salesorderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
